import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettierConfig from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'coverage/**',
      // Generated by `prisma generate` — not ours to lint.
      'src/generated/**',
      // Generated by `prisma migrate` — SQL, plus a lockfile we must not touch.
      'prisma/migrations/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        // Resolves each file's tsconfig on demand, so type-aware rules work
        // without maintaining a separate lint-only tsconfig.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // The brief bans `any` outright. Hard error, never a warning — a warning
      // is a rule nobody obeys.
      '@typescript-eslint/no-explicit-any': 'error',

      // Unused code is a review distraction. `_`-prefixed names are the
      // conventional opt-out, needed for unused GraphQL resolver parameters.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // Type-only imports are erased at build time; making that explicit keeps
      // runtime imports honest about what actually needs to exist.
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],

      // An unawaited promise in a resolver silently swallows failures.
      '@typescript-eslint/no-floating-promises': 'error',

      eqeqeq: ['error', 'always'],
    },
  },

  // This config file (and any other plain JS) sits outside tsconfig's `include`,
  // so type-aware rules have no program to consult.
  {
    files: ['**/*.mjs', '**/*.cjs', '**/*.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },

  // Must stay last: switches off stylistic rules that would fight Prettier.
  prettierConfig,
);
